# Generated by Django 4.1.7 on 2023-02-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GridOverview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateModel1',
            new_name='DateModel',
        ),
    ]
