# Generated by Django 4.1.7 on 2023-02-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridOverview', '0002_rename_datemodel1_datemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.FloatField()),
            ],
        ),
    ]
