# Generated by Django 4.1.7 on 2023-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridOverview', '0005_alter_totalpower_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.JSONField()),
            ],
        ),
    ]
