# Generated by Django 4.1.7 on 2023-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GridOverview', '0006_totalload'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='totalSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='totalWind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.JSONField()),
            ],
        ),
    ]
