# Generated by Django 4.1.7 on 2023-04-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GridOverview', '0008_batterypower_batterysoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterysoc',
            old_name='soc',
            new_name='level',
        ),
    ]
